// Generated by CoffeeScript 1.7.1
(function() {
  var currentWindowOnload, expose, startJasmine;

  expose = function(obj) {
    var key, _results;
    _results = [];
    for (key in obj) {
      _results.push(window[key] = obj[key]);
    }
    return _results;
  };

  expose(require('./lib/jasmine/jasmine.js'));

  require('./lib/jasmine-reporters/jasmine.tap_reporter.js');

  expose(require('./spec/SpecHelper'));

  require('./spec/SimpleSpec');

  describe('Browser Suite', function() {
    return it('Should pass a basic truthiness test.', function() {
      expect(true).toEqual(true);
      return expect(false).toEqual(false);
    });
  });

  startJasmine = function() {
    jasmine.getEnv().addReporter(new jasmine.TapReporter());
    return jasmine.getEnv().execute();
  };

  currentWindowOnload = window.onload;

  window.onload = function() {
    if (currentWindowOnload != null) {
      currentWindowOnload();
    }
    return setTimeout(startJasmine, 1);
  };

}).call(this);
